version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookhub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/books.sql:/docker-entrypoint-initdb.d/books.sql

volumes:
  mysql-data: