# .github/workflows/deploy.yml
name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          version: 'latest'
          namespace: default
          deployment: frontend
          image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy backend to Kubernetes
        uses: kubernetes/deploy-action@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          version: 'latest'
          namespace: default
          deployment: backend
          image: ${{ secrets.DOCKER_USERNAME }}/backend:latest