FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK data
RUN python -m nltk.downloader vader_lexicon
RUN python -m nltk.downloader punkt

# Copy application code
COPY . .

# Expose port
EXPOSE 5000

# Run command
CMD ["flask", "run", "--host=0.0.0.0"]